"""empty message

Revision ID: 017c24f07730
Revises: 0b2783e29336
Create Date: 2022-08-11 12:48:45.187307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '017c24f07730'
down_revision = '0b2783e29336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'show', 'artist', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'show', 'venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.drop_constraint(None, 'show', type_='foreignkey')
    # ### end Alembic commands ###
