"""empty message

Revision ID: 0b2783e29336
Revises: b1a6bfd3ca16
Create Date: 2022-08-10 09:19:05.375627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b2783e29336'
down_revision = 'b1a6bfd3ca16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('description', sa.String(), nullable=True))
    op.add_column('artist', sa.Column('website_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'website_link')
    op.drop_column('artist', 'description')
    # ### end Alembic commands ###
